package cpopartnersdk

// NotificationStationFeeJSONRequestBody defines body for NotificationStationFee for application/json ContentType.
type NotificationStationFeeJSONRequestBody NotificationStationFeeJSONBody
