package cpopartnersdk

// NotificationChargeOrderInfoJSONRequestBody defines body for NotificationChargeOrderInfo for application/json ContentType.
type NotificationChargeOrderInfoJSONRequestBody NotificationChargeOrderInfoJSONBody
