package cpopartnersdk

// NotificationStopChargeResultJSONRequestBody defines body for NotificationStopChargeResult for application/json ContentType.
type NotificationStopChargeResultJSONRequestBody NotificationStopChargeResultJSONBody
