package cpopartnersdk

// NotificationEquipChargeStatusJSONRequestBody defines body for NotificationEquipChargeStatus for application/json ContentType.
type NotificationEquipChargeStatusJSONRequestBody NotificationEquipChargeStatusJSONBody
