package cpopartnersdk

// NotificationStartChargeResultJSONRequestBody defines body for NotificationStartChargeResult for application/json ContentType.
type NotificationStartChargeResultJSONRequestBody NotificationStartChargeResultJSONBody
