package cpogovsdk

// QueryStationStatsUsingPOSTJSONRequestBody defines body for QueryStationStatsUsingPOST for application/json ContentType.
type QueryStationStatsUsingPOSTJSONRequestBody QueryStationStatsUsingPOSTJSONBody
