package cpogovsdk

// QueryStationInfoUsingPOSTJSONRequestBody defines body for QueryStationInfoUsingPOST for application/json ContentType.
type QueryStationInfoUsingPOSTJSONRequestBody QueryStationInfoUsingPOSTJSONBody
